### ISSUE TITLE
Allow someone to specify multiple games they want to play in 1 line

### ISSUE THREAD

**Issue by DanielOwen1** [JordanPowell/discord-play-register#14]
Like "id play cs/rl/squad"

I might have a go at this unless someone wants to do it

**Comment by JordanPowell** [comment]
I'll assign it to you for now - if you decide against doing it let us know (or unassign yourself if you can)

**Comment by LGregg11** [comment]
This has been completed now right? How come the issue still appears as open

**Comment by JordanPowell** [comment]
No PR was linked to it - #20 closed it but didn't mention it. I'll close now
